### ISSUE TITLE
Format of TraceFile 

### ISSUE THREAD

**Issue by arnvm** [SimpleSSD/SimpleSSD-Standalone#1]
Hello,

I wish to use SimpleSSD in Trace Replayer mode. Could you please help me with the format of the TraceFile?
Looking at the source code, I believe it is as follows:
`<timestamp> <logical sector address> <length (no of 4kB blocks)> <timestamp>`
1) Am I correct with the above assumption?
3) Is the timestamp field actually used? (With '[Tight](NumInstruction)' config enabled in config file)

Also, could you please help me with the significance of the hardcoded value (2 * 1024 * 1024 * 300) in the following line of code:
[address = (uint64_t)(address % (2 * 1024 * 1024 * 300)) * (uint64_t)512;](https://github.com/SimpleSSD/SimpleSSD-Standalone/blob/638fff4aef5ee62855f9fd3f484109964f65abdb/trace.cc#L55)

Thank you for your help.

**Comment by SimpleSSD** [comment]
Hi,

We use the traces from SNIA. The format follows:
<timestamp (in second)> <Read/Write> <logical sector address (in sector)> <length (number of sectors)> <duration (in second)>

The address range of SNIA trace can be bigger than the capacity of a single SSD. "(2 * 1024 * 1024 * 300)" is added to constrain the address range to 300GB.

Please let me know if you have more questions. @arnvm

**Comment by arnvm** [comment]
Thank You.
