### ISSUE TITLE
Has the flash power model been added to the project?

### ISSUE THREAD

**Issue by shengwenliang** [SimpleSSD/SimpleSSD-Standalone#1]
Hi，
   As the SimpleSSD website said, the Flash power model will be incorporated in version 2.0.0. And when I read the v2.0.0 code, I can't find the code about flash power model. So, the flash power model has been added to the project? Please guide me. Thanks.

**Comment by linwendi** [comment]
Maybe it is in [SimpleSSD-Standalone/simplessd/lib/mcpat](https://github.com/simplessd/mcpat)

**Comment by kukdh1** [comment]
Hi,

You can check code of NAND power model at
```
simplessd/pal/old/config.*
simplessd/pal/old/PALStatistics.*
simplessd/pal/old/Latency.*
```

As I presented at MICRO session, this NAND power model is quite simple,
just multiplying voltage, current and busy time of each components.

Thanks
