### ISSUE TITLE
meaning about a configuration parameter 

### ISSUE THREAD

**Issue by Chikorita7777** [SimpleSSD/SimpleSSD-Standalone#12]
### Explain what you want to ask here:
Hi,

In the given "Intel 750 400GB" and "Samsung Z-SSD prototype 800GB" configuration files, the number of HIL cores is 0.

What is the meaning of that the HIL core is 0? Does it mean that the HIL logic is implemented by kind of hardware and is fast enough to ignore latency?

Thanks.

**Comment by kukdh1** [comment]
Hi,

If core count is zero, it assume the such firmware part is implemented in hardware and set latency as zero.

For the Z-SSD, its controller has 5 cores and the host protocol handling is hardware accelerated.

For the Intel 750, the controller actually not hardware accelerated, but in the validation process, I set the HIL core as zero. (I cannot found how many cores in the controller)

** This question is related to SimpleSSD itself, not SimpleSSD-Standalone

Thanks.
