### ISSUE TITLE
Can we run multiple trace files simultaneously using NVMe interface?

### ISSUE THREAD

**Issue by Codeforfun29** [SimpleSSD/SimpleSSD-Standalone#13]
Hi,

I wanted to study interference behavior among simultaneously running workloads. Can we run two or more trace files?

**Comment by kukdh1** [comment]
Hi,

No, you need to manually merge two or more trace files into one trace file.

Thanks.

**Comment by SoumyaDandapat** [comment]
I am new to this, So can someone give me a trace file to use?
