### ISSUE TITLE
git submodule update --init --recursive fails

### ISSUE THREAD

**Issue by asimsalam** [SimpleSSD/SimpleSSD-Standalone#14]
Following the download and build instructions, the step to init the submodule simplessd fails:
git submodule update --init --recursive
Cloning into '/home/ssgroot/workspace/essd/simulator/ssd-simulator/SimpleSSD-Standalone/simplessd'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:simplessd/simplessd' into submodule path '<workspace>/SimpleSSD-Standalone/simplessd' failed
Failed to clone 'simplessd'. Retry scheduled
Cloning into '<workspace>/SimpleSSD-Standalone/simplessd'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:simplessd/simplessd' into submodule path '<workspace>/SimpleSSD-Standalone/simplessd' failed
Failed to clone 'simplessd' a second time, aborting

cat .gitmodules 
[submodule "simplessd"]
	path = simplessd
	url = git@github.com:simplessd/simplessd

**Comment by kukdh1** [comment]
Hi,

1. Check your internet connection
2. Check that you created SSH key to enable auto-login into github repository.

If you are not want to use SSH, you can replace path of `.gitignore` file from ssh to HTTPS.

Thanks.
