### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by alinezhad2018** [SimpleSSD/SimpleSSD-Standalone#15]
### Running Environment (please complete the following information):
 - Host OS and Kernel version: 
Red Hat Enterprise Linux Server release 7.6

> git show -s HEAD
commit 2f62058f9726093cd72ee5bf66a09156b981b9ee
Author: Donghyun Gouk <kukdh1@gmail.com>
Date:   Sun Feb 2 03:24:07 2020 +0900

    Release SimpleSSD Standalone version 2.0 Release Candidate 9

 - Compiler version used to build SimpleSSD-Standalone: [
> g++ --version
g++ (GCC) 5.4.0

 
### Explain what you want to ask here:
A clear explanation of your question.

I couldn't cmake the simpleSSD standalone

>>>cmake -DDEBUG_BUILD=off .
CMake Error at CMakeLists.txt:67 (message):
  GNU g++ < 4.9 does not support <regex>.Please update your compiler.

-- Configuring incomplete, errors occurred!
See also "/*/*/SimpleSSD-Standalone/CMakeFiles/CMakeOutput.log".

**Comment by kukdh1** [comment]
Hi,

Please check `cmake` correctly detects your compiler. `cmake` prints out your compiler version at the very beginning.
```
[kukdh1@kukdh1-workstation build]$ cmake ..
-- The C compiler identification is GNU 8.3.1
-- The CXX compiler identification is GNU 8.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
```

As you installed your GCC 5.4.0 from source, please try again with following cmdline.
```
CC=<full path to your gcc> CXX=<full path to your g++> cmake .
```

Thanks.

**Comment by alinezhad2018** [comment]
Thank you.
It has been solved by forcing the cmake using correct path for GCC and G++.
using this command:
cmake -DCMAKE_CXX_COMPILER=/the/path/gcc/5.4/bin/g++ -DCMAKE_C_COMPILER=/the/path/gcc/5.4/bin/gcc
