### ISSUE TITLE
support SATA?

### ISSUE THREAD

**Issue by sac2019** [SimpleSSD/SimpleSSD-Standalone#18]
Hi,
I run SimpleSSD Standalone v2.0,
when I  set the interface for sata in sample.cfg config file,
Interface = 2
I get this  message in the output:  Undefined interface specified.
Does it support sata?
I could run the same trace with the Interface = 2 (nvme) correctly.

thanks,,

**Comment by kukdh1** [comment]
Hi,

Currently, SATA interface is only supported by SimpleSSD-FullSystem -- As I don't uses SATA and UFS, I did not implemented it and it has very low priority on implementation plan.

You can implement on your own by looking current NVMe interface (`sil/nvme/*`) and FullSystem (`src/dev/storage/sata_interface.*`).

Thanks.
