### ISSUE TITLE
Requesting a trace file to run

### ISSUE THREAD

**Issue by SoumyaDandapat** [SimpleSSD/SimpleSSD-Standalone#19]
### Running Environment (please complete the following information):
 - Host OS and Kernel version:  Ubuntu 16.04 
 - Compiler version used to build SimpleSSD-Standalone:  GCC 5.4
 - SimpleSSD-Standalone version: v2.0-rc4 - 

### Execution information
- Standalone configuration file:
 Mode = 1 (Trace Replayer Mode)

### Explain what you want to ask here:
A clear explanation of your question.
So I am new to using this and Open source as well. I wanted to know how to create a trace file. Or if there is any trace file I can use.

**Comment by kukdh1** [comment]
Hi,

You can use any types of traces exist on public domain (e.g., [SNIA block trace](http://iotta.snia.org/tracetypes/3)).
Also you can collect trace by yourself (e.g., [blktrace](https://linux.die.net/man/8/blktrace)) and replay on SimpleSSD Standalone.

What only you need to do is, setting regular expression correctly to capture each line of trace file.

Thanks.
