### ISSUE TITLE
Cloning this repo fails. Expected release date of SimpleSSD-Standalone 2.0?

### ISSUE THREAD

**Issue by arnvm** [SimpleSSD/SimpleSSD-Standalone#2]
Hello,

While trying to obtain SimpleSSD's code, the command `git submodule update` fails with the following error:
`Fetched in submodule path 'simplessd', but it did not contain 33e23e2fa3218d467f0713b7242a0610549b18dc.`

I guess this is because v1 of SimpleSSD was removed from github.com/SimpleSSD/SimpleSSD. 

So, when is V2.0 of SimpleSSD-Standalone expected to be released?

Thank you for your help.

**Comment by SimpleSSD** [comment]
Hi, arnvm.

Sorry, We just fixed submodule link to correct one. (v1.0)

Because we are focused on full-system simulation, we are plan to release standalone v2.0 after stable release of fullsystem v2.0.
I think it will take one or two more months to stabilize fullsystem version.

Thanks.

**Comment by arnvm** [comment]
Thank you!
