### ISSUE TITLE
Question about source code for PAL

### ISSUE THREAD

**Issue by nobellant215** [SimpleSSD/SimpleSSD-Standalone#21]
Thanks for providing such a nice tool. 
I am trying to modify the source code to implement some features in the back-end flash memory. However I am stuck at the beginning of the PAL2.cc...

In the code below, what does SPDIV and PGDIV exactly mean and why are channel free slot's key values are set with such numbers. They are quite different from default flash timing parameters. 

```c++
  uint32_t SPDIV =
      c->readUint(SimpleSSD::CONFIG_PAL, SimpleSSD::PAL::NAND_DMA_SPEED) / 50;
  uint32_t PGDIV = 16384 / c->readUint(SimpleSSD::CONFIG_PAL,
                                       SimpleSSD::PAL::NAND_PAGE_SIZE);
```
```c++
case SimpleSSD::PAL::NAND_SLC:
        tmp = new std::map<uint64_t, uint64_t>;
        ChFreeSlots[i][100000 / SPDIV] = tmp;
        tmp = new std::map<uint64_t, uint64_t>;
        ChFreeSlots[i][100000 / SPDIV + 100000 / SPDIV] = tmp;
        tmp = new std::map<uint64_t, uint64_t>;
        ChFreeSlots[i][185000000 / (PGDIV * SPDIV)] = tmp;
        tmp = new std::map<uint64_t, uint64_t>;
        ChFreeSlots[i][185000000 / (PGDIV * SPDIV) + 100000 / SPDIV] = tmp;
        tmp = new std::map<uint64_t, uint64_t>;
        ChFreeSlots[i][1500000 / SPDIV] = tmp;
        break;
```

**Comment by kukdh1** [comment]
Hi,

For the `SPDIV` and `PGDIV`, original PAL developers may want to represent DMA speed (normally, MT/s in NAND spec) and page size (normally, 4KB ~ 16KB) in a small values (which are multiple of default values - 50MT/s and 16KB).

And these two `DIV` values are used for "binning" the timeline structure of PAL.
I think the constant values used here is quite heuristic -- they want to reduce searching time of empty timeslot of specific sizes and these values are determined by hand.

Just note that, as I didn't developed PAL (this part of codes are just copied from SimpleSSD 1.0, with a few minor fixes related to memory leakage), this answers may not exact.

If you want to add new operation to the NAND, I recommend you NOT TO modify timeline schedule algorithm.
Instead, please abstract your operation in `DMA0`, `MEM` and `DMA1` and add them to the NAND latency definition in `Latency*.cc`.
If `Latency` class returns correct latency value when a `GetLatency` function called, timeline scheduler will schedule your newly-added operations as normal NAND transactions.

Thanks.
