### ISSUE TITLE
Cannot find source file

### ISSUE THREAD

**Issue by RuixiangMa** [SimpleSSD/SimpleSSD-Standalone#3]
Hi,
 There exists a problem when I try to install your simulator, error information is followed below:
Cannot find source file:   simplessd/ini.h
Can you tell me how to solve this issue?
Best Regards.

**Comment by kukdh1** [comment]
Hi,

Did you initialized submodule? (The simplessd directory should not empty)
You can initialize and update submodule by following command:
```shell
git submodule update --init
```

Thanks.

**Comment by RuixiangMa** [comment]
Thanks for your help, I have resolved this problem.
