### ISSUE TITLE
complie error in SimpleSSD v2.0 

### ISSUE THREAD

**Issue by nsq974487195** [SimpleSSD/SimpleSSD-Standalone#3]
i follow the instruction in the website,

1.git clone $SOURCE
2.git submodule init
3.git submodule update
4.cmake .
5. make

when i input the instruction "cmke" , it occurs an errors and says that "Failed to find McPAT library.  Check you initialized submodules." 

would you help me to solve this problem ?

**Comment by KaCheung** [comment]
I'm guessing your lib/mcpat submodule didn't get pull as it's a submodule under simplessd
Try this command should resolve your problem:
git submodule update --init --recursive

**Comment by nsq974487195** [comment]
@KaCheung  thanks, it works.
