### ISSUE TITLE
parameters of config file

### ISSUE THREAD

**Issue by alinezhad2018** [SimpleSSD/SimpleSSD-Standalone#4]
hi,
is it possible to note the min value of the parameters of cfg file? for example the page size can't be less than 1024.... and maybe the plane number should be at least 2.... other values for these two parameters lead to core dump error....

regards

**Comment by kukdh1** [comment]
Hi,

We are not maintaining SimpleSSD 1.0, so no update will be performed to this repository until SimpleSSD-Standalone v2.1 released on public domain.

Limitation of page size can be adjusted in [this file](https://github.com/SimpleSSD/SimpleSSD/blob/d74fe803fc0c33f1682aca4b54ed1f0813c0e9b9/Latency.cc)
And the plane count can be 1, as I remember. (Although I fixed lots of bugs in v2.1)

Thanks.

**Comment by alinezhad2018** [comment]
hi,
is it supported different type of mapping? page map, block map?
i seems the code only support hybrid mapping....no parameters has been set for FTLMApping??
