### ISSUE TITLE
complie error in SimpleSSD v2.0

### ISSUE THREAD

**Issue by brian0603** [SimpleSSD/SimpleSSD-Standalone#4]
i follow the instruction in the website.
git clone git@github.com:simplessd/simplessd-standalone
cd simplessd-standalone
git checkout v2.0-rc3
git submodule update --init --recursive

when i input "git submodule update --init --recursive", it occurs the following problems

**Cloning into 'simplessd'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:simplessd/simplessd' into submodule path 'simplessd' failed**

have any clue can fix this problem?

**Comment by kukdh1** [comment]
Hi,

You need to register a SSH key to your GitHub account even when you pulling public repository.
See [GitHub help](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-ssh-urls).

Or modify repo url from ssh to https in `.gitmodules`.
