### ISSUE TITLE
Question about dedicated core count

### ISSUE THREAD

**Issue by urmydata** [SimpleSSD/SimpleSSD-Standalone#6]
Hi, 

I am currently using Amber for research, and I ran Amber while changing the number of dedicated cores.

I used a Samsung Z-SSD configuration file and a given request generator.

The results are as follows
https://docs.google.com/spreadsheets/d/12MnK_RR_xqME3nAAjEAorgbluP6vvPEBYsdiKioVB2E/edit?usp=sharing

The results show that bandwidth is not affected by the number of FTL cores.

One of logs about cores in the above experiment (sequential read, io depth = 32) is as follows
![image](https://user-images.githubusercontent.com/20039661/50947384-6539e180-14e1-11e9-8328-7db39b1946f1.png)

In that picture, icl core 0, ftl core 0, and 1 are idle.

I would like to know if Amber does not support changes based on the number of cores or it is just mistake.

Thanks

**Comment by kukdh1** [comment]
Hi,

As you can check the busy and idle cycle of FTL core, only one core for FTL is sufficient for handling all the requests.
Multiple cores can accelerate I/O handling if and only if the operation running on the core has utilization >= 100%.

Thanks.
