### ISSUE TITLE
Question about Cache Latency

### ISSUE THREAD

**Issue by urmydata** [SimpleSSD/SimpleSSD-Standalone#7]
Hi,

According to the code below, the cache latency is obtained by dividing the latency by the number of ICL cores. (icl/generic_cache.cc)
![image](https://user-images.githubusercontent.com/20039661/51008228-48a7b300-158e-11e9-80e2-199f2dccfe80.png)

Is the cache latency **actually** affected by the number of cores?

Thanks

**Comment by kukdh1** [comment]
Hi,

It depends on SSD firmware. (Cache latency of real SSD may not affected by # of core)
`GenericCache::getCacheLatency()` calculates cache lookup latency and current implementation assumes multi-threaded binary search.
I added such equation while in validation process.

Thanks.
