### ISSUE TITLE
Can you upload sample trace file?

### ISSUE THREAD

**Issue by Chikorita7777** [SimpleSSD/SimpleSSD-Standalone#8]
Hello. 

I would like to run the simulator using a trace file. 

Can you please upload sample trace file?

Thank you.

**Comment by kukdh1** [comment]
Hi,

SimpleSSD-Standalone can read trace files with various formats.
This feature is supported by following configurations.

```ini
[trace]
Regex = <Regular expression of trace file format>
Operation = <Group ID of Read/Write/Flush/Trim>
ByteOffset = <Group ID of Byte offset>
ByteLength = <Group ID of Byte length>
LBAOffset = <Group ID of LBA offset>
LBALength = <Group ID of LBA length>
Second = <Group ID of timestamp in unit of seconds>
Millisecond = <Group ID of timestamp in unit of milliseconds>
Microsecond = <Group ID of timestamp in unit of microseconds>
Nanosecond = <Group ID of timestamp in unit of nanoseconds>
Picosecond = <Group ID of timestamp in unit of picoseconds>
LBASize = <LBA size when LBAOffset and LBALength are used>
```

For more information, check the comments of example configuration file located in `config/sample.cfg`.
Also, you can check the source code `igl/trace/trace_replayer.cc`

Here are two example configurations.

### blkparse
Example of `blkparse` result:
```
8,16           1        1     1.427376394  5529    Q  WS 274432 + 8
8,16           1        2     1.427384090  5529    G  WS 274432 + 8
```
Example of regular expression for above file format:
```
Regex = "\d+,\d+ +\d+ +\d+ +(\d+).(\d+) +\d+ +D +(\w+) +(\d+) \+ (\d+)"
Operation = 3
LBAOffset = 4
LBALength = 5
Second = 1
Nanosecond = 2
LBASize = 512
```
(If `blkparse` result contains additional information such as process name, above regex may not work)

### SNIA trace
Example of MSPS trace:
```
0 0.702473 0 0                DiskRead 57805352 88
0 0.703072 0 0                DiskRead 59210920 8
```
Example of regular expression for above file format:
```
Regex = "\d (\d+).(\d+) \d \d +Disk(\w+) (\d+) (\d+)
Operation = 3
LBAOffset = 4
LBALength = 5
Second = 1
Microsecond = 2
LBASize = 512
```

You can download trace files from the internet, such as [SNIA iotta repository](http://iotta.snia.org/tracetypes/3).

Thanks.

**Comment by mayank-kabra2001** [comment]
Hi, I have used this sample blkparse output and parameters but the output stats still shows nothing. 
Is there an issue with trace file? Do I have to make it large enough ?

Following is the output.
********** Begin of simulation **********
0: info: SIL::None::Driver: Total SSD capacity: 412316860416 bytes
0: info: SIL::None::Driver: Logical Page Size: 32768 bytes
0: warn: No I/O submitted. Check regular expression.
