### ISSUE TITLE
What is the difference between lbaSize in trace file and lbsSize in SSD configuration file?

### ISSUE THREAD

**Issue by Chikorita7777** [SimpleSSD/SimpleSSD-Standalone#9]
Hi,

What is the difference between lbaSize in trace file and lbsSize in SSD configuration file?

Should they be the same?

Thank you

**Comment by kukdh1** [comment]
Hi,

They should be same. If not, the total data amount read/written will different with the trace file.

Let's assume that a trace file is collected from 512B sized LBA device and that trace file reads 10GB of data from underlying device.
If you simulate this trace file with LBASize = 4K, simulator will read 80GB of data from the underlying device.

Thanks.
